#!/usr/bin/python

import re

from ansible.module_utils.basic import *

def _escape_single_quotes(string):
    return re.sub("'", r"'\''", string)

def _set_value(module, key, value, argument_type):

    return module.run_command(" ".join([ '/usr/bin/gconftool-2 --set --type {} {} "{}"'.format(argument_type, _escape_single_quotes(key), value)]))

def _get_value(module, key):

    return module.run_command('gconftool-2 --get {}'.format(_escape_single_quotes(key)))[1].strip()


def main():

    module = AnsibleModule(
        argument_spec = {
            'state': { 'choices': ['present'], 'default': 'present' },
            'type': { 'choices': ['string', 'bool'], 'default': 'string' },
            'key': { 'required': True },
            'value': { 'required': True },
        },
        supports_check_mode = True,
    )

    params = module.params
    state = module.params['state']
    argument_type = module.params['type']
    key = module.params['key']
    value = module.params['value']

    old_value = _get_value(module, key)
    changed = old_value != value

    if changed and not module.check_mode:
        _set_value(module, key, value, argument_type)

    module.exit_json(changed=changed, key=key, type=argument_type, value=value, old_value=old_value)

main()